### ISSUE TITLE
Align active nav contents with the rest of the nav

### ISSUE THREAD

**Issue by JPablomr** [zwbetz-gh/cupper-hugo-theme#2]
I noticed that the active element in the nav for large screens does not align with the rest of the elements:

![not aligned nav](https://user-images.githubusercontent.com/629085/53140248-b95cca80-3551-11e9-88f7-09efce5ef701.png)

I'm not sure if this is by design, so feel free to ignore me if so. I am solving it with this:

```css
@media screen and (min-width: 768px) {
  .pattern [aria-current] {
    margin-left: 0.25em;
  }
}
```
![aligned nav](https://user-images.githubusercontent.com/629085/53140267-c7125000-3551-11e9-987f-1d1e51c60eda.png)

I'm not entirely sure what's the best way to implement this inside the code (I have an overrides.css file so I can keep pulling updates.)
