### ISSUE TITLE
Social icon links in footer

### ISSUE THREAD

**Issue by AnnaDodson** [zwbetz-gh/cupper-hugo-theme#45]
**Is your feature request related to a problem? Please describe.**
I wanted social links on my website so I included social icons in the footer

**Describe the solution you'd like**
I've already implemented this on my site using SVGs ([Super Tiny Icons](https://github.com/edent/SuperTinyIcons))
A demo is here: [anna-cupper-hugo-theme.netlify.app/](https://anna-cupper-hugo-theme.netlify.app/).
Template is here: [github.com/AnnaDodson/cupper-hugo-theme/blob/main/layouts/partials/social.html](https://github.com/AnnaDodson/cupper-hugo-theme/blob/main/layouts/partials/social.htmll)

**Describe alternatives you've considered**
Social links are only displayed if they exist in the config file so if a user doesn't want them, they don't need to add them.
Currently supporting the following out the box and users have the ability to add custom icons by providing the path to the SVGs or html partial.

```
params:  
  social:
    twitter: "TwitterName"
    gitlab: "GitLabName"
    github: "GitHubName"
    linkedin: "LinkedinName"
    email: "myemail@address.com"
    pinterest: "PinterestName"
    instagram: "InstagramName"
    reddit: "RedditSubreddit"
    slackinvite:
      name: "technottingham"
      code: "enQtNTgxNTYxMTExOTU5LTgxMDVjODUxYWI3MzNjOTJlMWUyMTYxNGEyNzYxNGYxNTExMWU0MmFkYjc5ZjI5MzY4ZmQ3MDdjZjdkNDg0ZDA"
    slackworkspace:
      name: "technottingham"
    facebook: "FacebookName"
    tiktok: "TikTokName"
    telephone: "0123456789"
    misc:
      - name: "Discord"
        url: "https://www.discord.com/"
        icon: "super-tiny-icons/discord.svg"
      - name: "YouTube"
        url: "https://youtube.com"
        icon: "super-tiny-icons/youtube.html"
```

**Additional context**
If you would like this feature, I will raise a PR for it.

![image](https://user-images.githubusercontent.com/14791708/97362768-6811ec00-1899-11eb-8d2f-752fbf953a7a.png)
