### ISSUE TITLE
Responsive/scrollable table.

### ISSUE THREAD

**Issue by datatemplar** [zwbetz-gh/cupper-hugo-theme#6]
**Is your feature request related to a problem? Please describe.**
I have a blog post with a big table (lot of text and entries). The display is chaotic with text going overthe columns.

**Describe the solution you'd like**
I would like to add a scrollbar when the text is to large for the table.

![annotation 2019-03-03 221035](https://user-images.githubusercontent.com/44871857/53701829-31a07700-3e01-11e9-9e16-52e3d1a5d85f.jpg)

 I propose to add these two line to the css relative to table. 

``` css
display: block;
overflow: scroll;
```

So the css will be like:

``` css
table {
    text-align: left;
    table-layout: fixed;
    width: 100%;
    border-collapse: collapse;
    display: block;
    overflow: scroll;
}
```

**Describe alternatives you've considered**
A second possibility is to create a shortcode. But I don't think it's necessary.
