### ISSUE TITLE
Font URL is relative to css directory

### ISSUE THREAD

**Issue by rnewman** [zwbetz-gh/cupper-hugo-theme#67]
This stylesheet:

https://github.com/zwbetz-gh/cupper-hugo-theme/blob/master/assets/css/template-styles.css#L4

refers to a font in path `css/fonts/`:

```css
/* Fonts */
@font-face {
    font-family: 'Miriam Libre';
    src: url('{{ "css/fonts/miriamlibre-bold.woff2" | absURL }}') format('woff2'), url('{{ "css/fonts/miriamlibre-bold.woff" | absURL }}') format('woff');
    font-weight: bold;
    font-style: normal;
}
```

This is built by Hugo into `public/css/styles.css`, where it looks like this:

```css
/* Fonts */
@font-face {
    font-family: 'Miriam Libre';
    src: url('css/fonts/miriamlibre-bold.woff2') format('woff2'), url('css/fonts/miriamlibre-bold.woff') format('woff');
    font-weight: bold;
    font-style: normal;
}
```

and Hugo puts the font directory next to it:

```
$ find public/css
public/css
public/css/styles.css
public/css/images
public/css/images/icon-tick.svg
public/css/images/stripe.svg
public/css/images/arrow_effect.svg
public/css/prism.css
public/css/search.fe0cd54a21628574bff49d721c827d1bb165ab56b0f22dd55ae78addbe61c309.css
public/css/fonts
public/css/fonts/miriamlibre-bold.woff2
public/css/fonts/miriamlibre-bold.woff
```

However, CSS paths are relative to the CSS file. That `@font-face.src` thus causes the browser to load `css/css/fonts/miriamlibre-bold.woff2`, which fails with a 404:

<img width="961" alt="Screen Shot 2022-01-05 at Jan 5 17 05 11 " src="https://user-images.githubusercontent.com/91722/148311711-b5ddf053-6fc1-4ea1-af6b-e2f10e42bab3.png">

This does **not** occur using `hugo server`.

I'm not sure if this is a Hugo bug (because it's clearly processing the CSS and the font) or a bug in the theme, but inserting `/` to turn it into `url('/css/fonts…')` or removing `css/` altogether from the `url` both cause correct CSS to be generated but break the behavior when loaded via `hugo server`.

**To Reproduce**

* Build an example Hugo site with this theme.
* Deploy it to Netlify or use a local HTTP server.

**Expected behavior**

The generated CSS refers to a correct path.

**Comment by zwbetz-gh** [comment]
Thanks for reporting this @rnewman. Am going to do some digging.

**Comment by zwbetz-gh** [comment]
Hmm. I am not able to reproduce this. 

For example, I have a demo of the theme deployed to Netlify. When I view the devtools for a sample post, all is fine. 

https://cupper-hugo-theme.netlify.app/cupper-shortcodes/

---

Then when I inspect the CSS, it is not as you say in your report. Instead, I see the full url for each font as expected. 

https://cupper-hugo-theme.netlify.app/css/styles.css

```css
/* Fonts */
@font-face {
    font-family: 'Miriam Libre';
    src: url('https://cupper-hugo-theme.netlify.app/css/fonts/miriamlibre-bold.woff2') format('woff2'), url('https://cupper-hugo-theme.netlify.app/css/fonts/miriamlibre-bold.woff') format('woff');
    font-weight: bold;
    font-style: normal;
}
```

---

For reference, the demo is currently built with hugo version 0.83.1

https://github.com/zwbetz-gh/cupper-hugo-theme/blob/1929b7a9c5828195730ddfdcc511b562e89346aa/netlify.toml#L6

**Comment by rnewman** [comment]
I wonder if this is a consequence of the relativeURLs setting?

**Comment by zwbetz-gh** [comment]
Is your base url set in your config file?

Actually, for me to debug this further, you will need to link to your site
source code, upload a zip, or at least post your config file.

**Comment by rnewman** [comment]
OK, I built [a repro](https://github.com/rnewman/hugo-example/blob/main/config.yaml#L1), but I think I also figured this out.

`hugo server` replaces your `baseURL` (which causes [no end of confusion for users](https://duckduckgo.com/?t=ffab&q=hugo+baseurl&ia=web)).

It's [not documented](https://gohugo.io/getting-started/configuration/#baseurl) what the right value should be when deploying for multiple names (as is the case when deploying to staging, or to Netlify with and without an external DNS name) or without hardcoding a particular base URL: advice varies between the empty string, a slash, or using scripts to override it when building.

I had chosen the empty string, and everything works except for this.

Using `baseURL: "/"` makes my simple case work.

However, it's still not clear what the right thing should be if I were to deploy into a path, and thus need real relative URL support.

Changing the stylesheet to:

```css
/* Fonts */
@font-face {
    font-family: 'Miriam Libre';
    src: url('{{ "../css/fonts/miriamlibre-bold.woff2" | absURL }}') format('woff2'), url('{{ "../css/fonts/miriamlibre-bold.woff" | absURL }}') format('woff');
    font-weight: bold;
    font-style: normal;
}
```

makes _both_ `""` and `"/"` work as the value of `baseURL`; perhaps consider changing this?

https://inspiring-franklin-01af8a.netlify.app/ is a Netlify deploy of my repro case with that commit stacked on top. The font is correct in both `hugo server` and in the deploy.
